[package]
  cjc-version = "1.1.0"
  name = "linderHttp"
  description = "nothing here"
  version = "0.1.0"
  target-dir = ""
  src-dir = ""
  output-type = "static"
  override-compile-option = ""
  link-option = ""
  [package.package-configuration]

[dependencies]
  stdx_encode = {path = "D:\\linderSeline\\projects\\Cangjie\\standstdx\\stdx_standalone_encode"}
  stdx_encode_json = {path = "D:\\linderSeline\\projects\\Cangjie\\standstdx\\stdx_standalone_encode_json"}
  stdx_net = {path = "D:\\linderSeline\\projects\\Cangjie\\standstdx\\stdx_standalone_net"}
  stdx_serialization = {path = "D:\\linderSeline\\projects\\Cangjie\\standstdx\\stdx_standalone_serialization"}
  